Content Management System Features
kuri-team/yabe-mall pull request #53
Opened 2021-05-19 18:29 UTC by miketvo

Changes:

- Moved bio section of the About Us page into `about-us-bio.php` (modularization)
- Added flock() to file write code for more security
- Implemented bio editing for CMS About Us Editor
- Implemented CMS About Us Editor member photo changing
- Renamed ~~Page Editor~~ to **Edit Legal Information**
- Added a shared `page-editor.php` common PHP module in private/shared
- Modularization of legal pages in:
    - `private/shared/legal/copyright.php`
    - `private/shared/legal/tos.php`
    - `private/shared/legal/privacy-policy.php`
- Implemented "Edit Legal Information" CMS page

2021-05-19 23:51 UTC, rider3458 approved these changes

2021-05-20 01:12 UTC, tnathu-ai submitted a review, later dismissed

2021-05-20 03:14 UTC, doanyennhi requested changes

2021-05-20 03:14 UTC, doanyennhi commented on public/admin/index.php
>          <p class="text-align-justify">CMS stands for Content Management System. You can use the administrative tools provided here to modify website database, configure website settings, add/remove a
You didn't add the Manual's href link here

2021-05-20 06:43 UTC, doanyennhi approved these changes

2021-05-20 07:56 UTC, tnathu-ai approved these changes

2021-05-20 07:57 UTC, merged